#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: false

language: cpp

matrix:
  include:
    - env: COMPILER_VERSION=4.8
      os: linux
      compiler: g++
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - kalakris-cmake
          - ubuntu-sdk-team
          packages:
          - g++-4.8
          - cmake
          - libglib2.0-dev
    - env: COMPILER_VERSION=3.5
      os: linux
      compiler: clang++
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.5
          packages:
          - clang-3.5
          - cmake
          - libglib2.0-dev


before_script:
  - mkdir build
  - cd build
  - CC=$CC-${COMPILER_VERSION} CXX=$CXX-${COMPILER_VERSION} cmake -DBUILD_TESTS=True ..
  - cd ..

script:
  - cd build
  - make -k -j2 VERBOSE=1
  - ctest --output-on-failure
