[package]
name = "sdcv"
version = "0.1.0"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]

[dependencies]
getopts = "0.2"
gettext = "0.2.0"
rust-ini = "0.9.5"
byteorder = "0.5"
libc = "0.2.14"
flate2 = "0.2"